inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/*'
Lint/UnusedMethodArgument:
  Exclude:
    - "lib/geoserver/publish/style.rb"
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
Naming/FileName:
  Exclude:
    - "geoserver-publish.gemspec"
    - "Gemfile"
Style/StringLiterals:
  EnforcedStyle: double_quotes
